/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lcalc.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\10\1\11\1\1\22\0\1\34\1\50\1\6"+
    "\5\0\1\55\1\56\1\61\1\57\1\54\1\60\1\0\1\63\12\4"+
    "\1\0\1\53\1\46\1\45\1\47\2\0\32\5\1\0\1\7\2\0"+
    "\1\5\1\0\1\15\1\30\1\36\1\21\1\13\1\5\1\41\1\42"+
    "\1\31\1\5\1\37\1\25\1\44\1\16\1\17\1\43\1\5\1\23"+
    "\1\33\1\20\1\24\1\12\1\5\1\32\1\14\1\40\1\51\1\0"+
    "\1\52\7\0\1\10\160\0\1\62\5\0\1\35\42\0\1\22\21\0"+
    "\1\26\55\0\1\27\u1ec8\0\1\10\1\10\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\1\17\4\1\5"+
    "\1\6\1\7\1\1\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\0\1\22\1\0"+
    "\1\23\2\0\15\4\1\0\5\4\1\0\1\4\1\24"+
    "\1\25\1\26\1\27\1\4\2\0\2\4\1\0\1\30"+
    "\3\4\1\31\2\4\2\0\3\4\1\0\1\4\1\0"+
    "\1\32\1\33\3\4\1\34\1\4\1\35\1\36\1\37"+
    "\1\40\1\4\1\0\5\4\2\0\3\4\1\0\1\4"+
    "\1\0\4\4\2\0\1\41\1\0\1\4\2\0\1\4"+
    "\1\42\1\0\1\43\3\4\1\44\1\45\1\46\1\0"+
    "\1\47\3\4\1\0\1\50\1\0\1\4\4\0\2\4"+
    "\1\51\1\0\3\4\2\0\1\4\4\0\1\52\1\53"+
    "\1\0\3\4\1\0\1\54\1\55\2\0\1\56\2\0"+
    "\2\4\1\57\1\0\1\60\1\0\1\61\1\0\1\62"+
    "\1\4\1\63\2\0\1\4\2\0\1\64\2\0\1\65"+
    "\3\0\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[200];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\64\0\234\0\320\0\u0104\0\u0138"+
    "\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8"+
    "\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478"+
    "\0\u04ac\0\u04e0\0\64\0\64\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\u0104\0\64\0\u0514\0\u0548"+
    "\0\u057c\0\u05b0\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8"+
    "\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888"+
    "\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4\0\64"+
    "\0\64\0\64\0\64\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8"+
    "\0\u0b2c\0\320\0\u0b60\0\u0b94\0\u0bc8\0\320\0\u0bfc\0\u0c30"+
    "\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0"+
    "\0\320\0\320\0\u0e04\0\u0e38\0\u0e6c\0\64\0\u0ea0\0\320"+
    "\0\64\0\u0ed4\0\320\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8"+
    "\0\u100c\0\u1040\0\u1074\0\u10a8\0\u10dc\0\u1110\0\u1144\0\u1178"+
    "\0\u11ac\0\u11e0\0\u1214\0\u1248\0\u127c\0\u12b0\0\u12e4\0\u1318"+
    "\0\64\0\u134c\0\u1380\0\u13b4\0\u13e8\0\u141c\0\64\0\u1450"+
    "\0\64\0\u1484\0\u14b8\0\u14ec\0\320\0\64\0\320\0\u1520"+
    "\0\320\0\u1554\0\u1588\0\u15bc\0\u15f0\0\64\0\u1624\0\u1658"+
    "\0\u168c\0\u16c0\0\u16f4\0\u1728\0\u175c\0\u1790\0\320\0\u17c4"+
    "\0\u17f8\0\u182c\0\u1860\0\u1894\0\u18c8\0\u18fc\0\u1930\0\u1964"+
    "\0\u1998\0\u19cc\0\320\0\320\0\u1a00\0\u1a34\0\u1a68\0\u1a9c"+
    "\0\u1ad0\0\64\0\320\0\u1b04\0\u1b38\0\64\0\u1b6c\0\u1ba0"+
    "\0\u1bd4\0\u1c08\0\320\0\u1c3c\0\64\0\u1c70\0\64\0\u1ca4"+
    "\0\320\0\u1cd8\0\64\0\u1d0c\0\u1d40\0\u1d74\0\u1da8\0\u1ddc"+
    "\0\320\0\u1e10\0\u1e44\0\64\0\u1e78\0\u1eac\0\u1ee0\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[200];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\2\2\1\4"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\6\1\16"+
    "\1\2\1\17\1\6\1\20\2\2\1\21\1\22\1\6"+
    "\1\23\1\4\1\2\1\24\1\25\3\6\1\26\1\6"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\2\1\44\66\0"+
    "\1\4\65\0\1\5\63\0\2\6\4\0\10\6\1\0"+
    "\3\6\2\0\4\6\2\0\7\6\17\0\6\45\1\46"+
    "\1\47\54\45\4\0\2\6\4\0\1\6\1\50\6\6"+
    "\1\0\3\6\2\0\4\6\2\0\7\6\23\0\2\6"+
    "\4\0\10\6\1\51\3\6\1\0\1\52\2\6\1\53"+
    "\1\6\2\0\7\6\23\0\2\6\4\0\3\6\1\54"+
    "\4\6\1\0\3\6\2\0\4\6\2\0\7\6\23\0"+
    "\2\6\4\0\10\6\1\0\1\55\2\6\2\0\4\6"+
    "\2\0\2\6\1\56\4\6\23\0\2\6\4\0\5\6"+
    "\1\57\2\6\1\0\3\6\2\0\4\6\2\0\7\6"+
    "\23\0\2\6\4\0\10\6\1\0\2\6\1\60\2\0"+
    "\4\6\2\0\7\6\23\0\2\6\4\0\1\6\1\61"+
    "\3\6\1\62\2\6\1\0\3\6\2\0\4\6\2\0"+
    "\7\6\23\0\2\6\4\0\1\6\1\63\6\6\1\0"+
    "\3\6\2\0\4\6\2\0\7\6\23\0\2\6\4\0"+
    "\1\6\1\64\6\6\1\0\3\6\2\0\1\6\1\65"+
    "\2\6\2\0\7\6\23\0\2\6\4\0\3\6\1\66"+
    "\4\6\1\0\3\6\2\0\1\6\1\67\2\6\2\0"+
    "\7\6\15\0\1\70\5\0\2\6\4\0\10\6\1\0"+
    "\2\6\1\71\2\0\3\6\1\72\2\0\7\6\23\0"+
    "\2\6\4\0\5\6\1\73\2\6\1\0\1\6\1\74"+
    "\1\6\2\0\4\6\2\0\7\6\23\0\2\6\4\0"+
    "\5\6\1\75\2\6\1\0\3\6\2\0\4\6\2\0"+
    "\7\6\23\0\2\6\4\0\10\6\1\0\3\6\1\76"+
    "\1\0\4\6\2\0\7\6\23\0\2\6\4\0\5\6"+
    "\1\77\2\6\1\0\3\6\2\0\4\6\2\0\7\6"+
    "\64\0\1\100\63\0\1\101\63\0\1\102\63\0\1\103"+
    "\16\0\1\45\2\0\5\45\2\0\52\45\4\0\2\6"+
    "\4\0\2\6\1\104\5\6\1\0\3\6\2\0\4\6"+
    "\2\0\7\6\32\0\1\105\101\0\1\106\36\0\2\6"+
    "\4\0\10\6\1\0\3\6\2\0\1\6\1\107\2\6"+
    "\2\0\7\6\23\0\2\6\4\0\4\6\1\110\3\6"+
    "\1\0\3\6\2\0\4\6\1\111\1\0\2\6\1\112"+
    "\4\6\23\0\2\6\4\0\3\6\1\113\2\6\1\114"+
    "\1\6\1\0\3\6\2\0\4\6\2\0\7\6\23\0"+
    "\2\6\4\0\3\6\1\115\4\6\1\0\3\6\2\0"+
    "\4\6\2\0\7\6\23\0\2\6\4\0\6\6\1\116"+
    "\1\6\1\0\3\6\2\0\4\6\2\0\7\6\23\0"+
    "\2\6\4\0\7\6\1\117\1\0\3\6\2\0\4\6"+
    "\2\0\7\6\23\0\2\6\4\0\1\120\7\6\1\121"+
    "\3\6\2\0\4\6\2\0\7\6\23\0\2\6\4\0"+
    "\10\6\1\122\3\6\2\0\4\6\2\0\7\6\23\0"+
    "\2\6\4\0\3\6\1\123\4\6\1\0\3\6\2\0"+
    "\4\6\2\0\7\6\23\0\2\6\4\0\4\6\1\124"+
    "\3\6\1\0\3\6\2\0\4\6\2\0\7\6\23\0"+
    "\2\6\4\0\10\6\1\0\3\6\2\0\3\6\1\125"+
    "\2\0\7\6\23\0\2\6\4\0\10\6\1\0\3\6"+
    "\1\0\1\126\4\6\2\0\7\6\23\0\2\6\4\0"+
    "\6\6\1\127\1\6\1\0\3\6\2\0\4\6\2\0"+
    "\7\6\44\0\1\130\42\0\2\6\4\0\1\6\1\131"+
    "\6\6\1\0\3\6\2\0\4\6\2\0\7\6\23\0"+
    "\2\6\4\0\1\6\1\132\6\6\1\0\3\6\2\0"+
    "\4\6\2\0\7\6\23\0\2\6\4\0\4\6\1\133"+
    "\3\6\1\0\3\6\2\0\4\6\2\0\7\6\23\0"+
    "\2\6\4\0\10\6\1\0\3\6\2\0\1\134\3\6"+
    "\2\0\7\6\23\0\2\6\4\0\4\6\1\135\3\6"+
    "\1\0\3\6\2\0\4\6\2\0\7\6\42\0\1\136"+
    "\44\0\2\6\4\0\10\6\1\0\3\6\2\0\3\6"+
    "\1\137\2\0\7\6\23\0\2\6\4\0\3\6\1\140"+
    "\4\6\1\0\3\6\2\0\4\6\2\0\7\6\42\0"+
    "\1\141\60\0\1\142\47\0\2\6\4\0\6\6\1\143"+
    "\1\6\1\0\3\6\2\0\4\6\2\0\7\6\23\0"+
    "\2\6\4\0\10\6\1\0\2\6\1\144\2\0\4\6"+
    "\2\0\7\6\40\0\1\145\46\0\2\6\4\0\10\6"+
    "\1\0\3\6\2\0\3\6\1\146\2\0\7\6\23\0"+
    "\2\6\4\0\3\6\1\147\4\6\1\0\3\6\2\0"+
    "\4\6\2\0\7\6\23\0\2\6\4\0\10\6\1\0"+
    "\2\6\1\150\2\0\4\6\2\0\7\6\23\0\2\6"+
    "\4\0\10\6\1\0\1\6\1\151\1\6\2\0\4\6"+
    "\2\0\7\6\23\0\2\6\4\0\3\6\1\152\4\6"+
    "\1\0\3\6\2\0\4\6\2\0\7\6\50\0\1\153"+
    "\55\0\1\154\44\0\2\6\4\0\7\6\1\155\1\0"+
    "\3\6\2\0\4\6\2\0\7\6\23\0\2\6\4\0"+
    "\10\6\1\0\3\6\2\0\4\6\2\0\3\6\1\156"+
    "\3\6\23\0\2\6\4\0\6\6\1\157\1\6\1\0"+
    "\3\6\2\0\4\6\2\0\7\6\44\0\1\160\42\0"+
    "\2\6\4\0\10\6\1\0\3\6\2\0\1\6\1\161"+
    "\2\6\2\0\7\6\54\0\1\162\32\0\2\6\4\0"+
    "\10\6\1\0\1\163\2\6\2\0\4\6\2\0\7\6"+
    "\23\0\2\6\4\0\10\6\1\0\3\6\2\0\3\6"+
    "\1\164\2\0\7\6\23\0\2\6\4\0\10\6\1\0"+
    "\3\6\2\0\4\6\2\0\1\165\6\6\23\0\2\6"+
    "\4\0\10\6\1\0\3\6\2\0\1\6\1\166\2\6"+
    "\2\0\7\6\53\0\1\167\33\0\2\6\4\0\10\6"+
    "\1\0\3\6\1\170\1\0\4\6\2\0\7\6\34\0"+
    "\1\171\52\0\2\6\4\0\10\6\1\0\3\6\1\172"+
    "\1\0\4\6\2\0\7\6\23\0\2\6\4\0\10\6"+
    "\1\0\1\173\2\6\2\0\4\6\2\0\7\6\23\0"+
    "\2\6\4\0\10\6\1\0\3\6\1\174\1\0\4\6"+
    "\2\0\7\6\23\0\2\6\4\0\10\6\1\175\3\6"+
    "\2\0\4\6\2\0\7\6\23\0\2\6\4\0\10\6"+
    "\1\0\3\6\2\0\4\6\2\0\6\6\1\176\44\0"+
    "\1\177\1\0\1\200\60\0\1\201\43\0\2\6\4\0"+
    "\10\6\1\0\3\6\2\0\1\6\1\202\1\6\1\203"+
    "\2\0\7\6\23\0\2\6\4\0\6\6\1\204\1\6"+
    "\1\0\3\6\2\0\4\6\2\0\7\6\23\0\2\6"+
    "\4\0\1\6\1\205\6\6\1\0\3\6\2\0\4\6"+
    "\2\0\7\6\34\0\1\206\52\0\2\6\4\0\10\6"+
    "\1\0\1\207\2\6\2\0\4\6\2\0\7\6\63\0"+
    "\1\210\23\0\2\6\4\0\3\6\1\211\4\6\1\0"+
    "\3\6\2\0\4\6\2\0\7\6\23\0\2\6\4\0"+
    "\6\6\1\212\1\6\1\0\3\6\2\0\4\6\2\0"+
    "\7\6\23\0\2\6\4\0\3\6\1\213\4\6\1\0"+
    "\3\6\2\0\4\6\2\0\7\6\23\0\2\6\4\0"+
    "\6\6\1\214\1\6\1\0\3\6\2\0\4\6\2\0"+
    "\7\6\40\0\1\215\71\0\1\216\52\0\1\217\51\0"+
    "\2\6\4\0\10\6\1\0\3\6\2\0\4\6\2\0"+
    "\1\6\1\220\5\6\42\0\1\221\64\0\1\222\43\0"+
    "\2\6\4\0\10\6\1\0\3\6\2\0\4\6\1\223"+
    "\1\0\7\6\56\0\1\224\30\0\2\6\4\0\4\6"+
    "\1\225\3\6\1\0\3\6\2\0\4\6\2\0\7\6"+
    "\23\0\2\6\4\0\6\6\1\226\1\6\1\0\3\6"+
    "\2\0\4\6\2\0\7\6\23\0\2\6\4\0\10\6"+
    "\1\0\3\6\2\0\4\6\2\0\4\6\1\227\2\6"+
    "\54\0\1\230\32\0\2\6\4\0\10\6\1\0\1\231"+
    "\2\6\2\0\4\6\2\0\7\6\23\0\2\6\4\0"+
    "\6\6\1\232\1\6\1\0\3\6\2\0\4\6\2\0"+
    "\7\6\23\0\2\6\4\0\10\6\1\0\3\6\2\0"+
    "\1\6\1\233\2\6\2\0\7\6\32\0\1\234\71\0"+
    "\1\235\46\0\2\6\4\0\1\6\1\236\6\6\1\0"+
    "\3\6\2\0\4\6\2\0\7\6\56\0\1\237\60\0"+
    "\1\240\42\0\1\241\63\0\1\242\54\0\2\6\4\0"+
    "\6\6\1\243\1\6\1\0\3\6\2\0\4\6\2\0"+
    "\7\6\23\0\2\6\4\0\10\6\1\0\1\244\2\6"+
    "\2\0\4\6\2\0\7\6\35\0\1\245\51\0\2\6"+
    "\4\0\10\6\1\0\3\6\2\0\1\6\1\246\2\6"+
    "\2\0\7\6\23\0\2\6\4\0\1\6\1\247\6\6"+
    "\1\0\3\6\2\0\4\6\2\0\7\6\23\0\2\6"+
    "\4\0\5\6\1\250\2\6\1\0\3\6\2\0\4\6"+
    "\2\0\7\6\41\0\1\251\56\0\1\252\52\0\2\6"+
    "\4\0\4\6\1\253\3\6\1\0\3\6\2\0\4\6"+
    "\2\0\7\6\32\0\1\254\103\0\1\255\50\0\1\256"+
    "\61\0\1\257\66\0\1\260\46\0\2\6\4\0\4\6"+
    "\1\261\3\6\1\0\3\6\2\0\4\6\2\0\7\6"+
    "\23\0\2\6\4\0\4\6\1\262\3\6\1\0\3\6"+
    "\2\0\4\6\2\0\7\6\23\0\2\6\4\0\4\6"+
    "\1\263\3\6\1\0\3\6\2\0\4\6\2\0\7\6"+
    "\50\0\1\264\50\0\1\265\102\0\1\266\57\0\1\267"+
    "\45\0\1\270\54\0\2\6\4\0\10\6\1\0\3\6"+
    "\2\0\4\6\2\0\3\6\1\271\3\6\23\0\2\6"+
    "\4\0\3\6\1\272\4\6\1\0\3\6\2\0\4\6"+
    "\2\0\7\6\44\0\1\273\61\0\1\274\56\0\1\275"+
    "\51\0\2\6\4\0\6\6\1\276\1\6\1\0\3\6"+
    "\2\0\4\6\2\0\7\6\32\0\1\277\104\0\1\300"+
    "\33\0\2\6\4\0\1\6\1\301\6\6\1\0\3\6"+
    "\2\0\4\6\2\0\7\6\55\0\1\302\64\0\1\303"+
    "\37\0\1\304\65\0\1\305\73\0\1\306\53\0\1\307"+
    "\64\0\1\310\45\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7956];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\26\1\12\11\1\0\1\11"+
    "\1\0\1\1\2\0\15\1\1\0\5\1\1\0\1\1"+
    "\4\11\1\1\2\0\2\1\1\0\7\1\2\0\3\1"+
    "\1\0\1\1\1\0\5\1\1\11\2\1\1\11\3\1"+
    "\1\0\5\1\2\0\3\1\1\0\1\1\1\0\4\1"+
    "\2\0\1\11\1\0\1\1\2\0\1\1\1\11\1\0"+
    "\1\11\4\1\1\11\1\1\1\0\4\1\1\0\1\11"+
    "\1\0\1\1\4\0\3\1\1\0\3\1\2\0\1\1"+
    "\4\0\2\1\1\0\3\1\1\0\1\11\1\1\2\0"+
    "\1\11\2\0\3\1\1\0\1\11\1\0\1\11\1\0"+
    "\2\1\1\11\2\0\1\1\2\0\1\1\2\0\1\11"+
    "\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[200];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 186) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(sym.EOF);
            }
            case 201: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <"+yytext()+">");
            }
          case 55: break;
          case 2: 
            { /* do nothing */
            }
          case 56: break;
          case 3: 
            { return symbol(sym.NUM, new Integer(yytext()));
            }
          case 57: break;
          case 4: 
            { return symbol(sym.IDENT, new String(yytext()));
            }
          case 58: break;
          case 5: 
            { return symbol(sym.ASSIGN);
            }
          case 59: break;
          case 6: 
            { return symbol(sym.LT);
            }
          case 60: break;
          case 7: 
            { return symbol(sym.GT);
            }
          case 61: break;
          case 8: 
            { return symbol(sym.LCURLY);
            }
          case 62: break;
          case 9: 
            { return symbol(sym.RCURLY);
            }
          case 63: break;
          case 10: 
            { return symbol(sym.SEMI);
            }
          case 64: break;
          case 11: 
            { return symbol(sym.COMMA);
            }
          case 65: break;
          case 12: 
            { return symbol(sym.LPAREN);
            }
          case 66: break;
          case 13: 
            { return symbol(sym.RPAREN);
            }
          case 67: break;
          case 14: 
            { return symbol(sym.PLUS);
            }
          case 68: break;
          case 15: 
            { return symbol(sym.MINUS);
            }
          case 69: break;
          case 16: 
            { return symbol(sym.TIMES);
            }
          case 70: break;
          case 17: 
            { return symbol(sym.DIVIDE);
            }
          case 71: break;
          case 18: 
            { return symbol(sym.STRING, new String(yytext()));
            }
          case 72: break;
          case 19: 
            { return symbol(sym.AND);
            }
          case 73: break;
          case 20: 
            { return symbol(sym.EQ);
            }
          case 74: break;
          case 21: 
            { return symbol(sym.LE);
            }
          case 75: break;
          case 22: 
            { return symbol(sym.GE);
            }
          case 76: break;
          case 23: 
            { return symbol(sym.NE);
            }
          case 77: break;
          case 24: 
            { return symbol(sym.YAZ);
            }
          case 78: break;
          case 25: 
            { return symbol(sym.NOT);
            }
          case 79: break;
          case 26: 
            { return symbol(sym.ILE);
            }
          case 80: break;
          case 27: 
            { return symbol(sym.ISE);
            }
          case 81: break;
          case 28: 
            { return symbol(sym.BREAK);
            }
          case 82: break;
          case 29: 
            { return symbol(sym.OR);
            }
          case 83: break;
          case 30: 
            { return symbol(sym.EGER);
            }
          case 84: break;
          case 31: 
            { return symbol(sym.STREQ);
            }
          case 85: break;
          case 32: 
            { return symbol(sym.EXIT);
            }
          case 86: break;
          case 33: 
            { return symbol(sym.YADA);
            }
          case 87: break;
          case 34: 
            { return symbol(sym.DEGIL);
            }
          case 88: break;
          case 35: 
            { return symbol(sym.TRUE);
            }
          case 89: break;
          case 36: 
            { return symbol((sym.LIST));
            }
          case 90: break;
          case 37: 
            { return symbol(sym.BEGIN);
            }
          case 91: break;
          case 38: 
            { return symbol(sym.END);
            }
          case 92: break;
          case 39: 
            { return symbol(sym.SONRA);
            }
          case 93: break;
          case 40: 
            { return symbol(sym.FALSE);
            }
          case 94: break;
          case 41: 
            { return symbol(sym.LENGTH);
            }
          case 95: break;
          case 42: 
            { return symbol(sym.READINT);
            }
          case 96: break;
          case 43: 
            { return symbol(sym.READSTR);
            }
          case 97: break;
          case 44: 
            { return symbol(sym.ARASINDA);
            }
          case 98: break;
          case 45: 
            { return symbol(sym.ART);
            }
          case 99: break;
          case 46: 
            { return symbol(sym.CONTINUE);
            }
          case 100: break;
          case 47: 
            { return symbol(sym.POSITION);
            }
          case 101: break;
          case 48: 
            { return symbol(sym.AZ);
            }
          case 102: break;
          case 49: 
            { return symbol(sym.DEGIS);
            }
          case 103: break;
          case 50: 
            { return symbol(sym.SUBSTRING);
            }
          case 104: break;
          case 51: 
            { return symbol(sym.STRNOTEQ);
            }
          case 105: break;
          case 52: 
            { return symbol(sym.CONCATENATE);
            }
          case 106: break;
          case 53: 
            { return symbol(sym.WHILE);
            }
          case 107: break;
          case 54: 
            { return symbol(sym.MODE);
            }
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
