
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRNOTEQ = 41;
  public static final int ILE = 17;
  public static final int DIVIDE = 49;
  public static final int SUBSTRING = 31;
  public static final int READSTR = 29;
  public static final int FUNCTION = 23;
  public static final int GE = 38;
  public static final int CONCATENATE = 30;
  public static final int YADA = 14;
  public static final int READINT = 26;
  public static final int ARASINDA = 18;
  public static final int LPAREN = 51;
  public static final int SEMI = 44;
  public static final int CONTINUE = 19;
  public static final int SONRA = 7;
  public static final int MINUS = 47;
  public static final int RPAREN = 52;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int LT = 35;
  public static final int OR = 3;
  public static final int COMMA = 45;
  public static final int BEGIN = 8;
  public static final int LISTE = 56;
  public static final int NUM = 53;
  public static final int PLUS = 46;
  public static final int EXIT = 10;
  public static final int ASSIGN = 33;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int YAZ = 25;
  public static final int MODE = 50;
  public static final int LCURLY = 21;
  public static final int IDENT = 54;
  public static final int BREAK = 20;
  public static final int EQ = 34;
  public static final int RCURLY = 22;
  public static final int TIMES = 48;
  public static final int EGER = 11;
  public static final int POSITION = 28;
  public static final int ISE = 12;
  public static final int WHILE = 15;
  public static final int LIST = 32;
  public static final int DEGIS = 16;
  public static final int NE = 39;
  public static final int ART = 42;
  public static final int AZ = 43;
  public static final int END = 9;
  public static final int STRING = 55;
  public static final int DEGIL = 13;
  public static final int STREQ = 40;
  public static final int FALSE = 6;
  public static final int GT = 37;
  public static final int LENGTH = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "SONRA",
  "BEGIN",
  "END",
  "EXIT",
  "EGER",
  "ISE",
  "DEGIL",
  "YADA",
  "WHILE",
  "DEGIS",
  "ILE",
  "ARASINDA",
  "CONTINUE",
  "BREAK",
  "LCURLY",
  "RCURLY",
  "FUNCTION",
  "RETURN",
  "YAZ",
  "READINT",
  "LENGTH",
  "POSITION",
  "READSTR",
  "CONCATENATE",
  "SUBSTRING",
  "LIST",
  "ASSIGN",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "STREQ",
  "STRNOTEQ",
  "ART",
  "AZ",
  "SEMI",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODE",
  "LPAREN",
  "RPAREN",
  "NUM",
  "IDENT",
  "STRING",
  "LISTE"
  };
}

