
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRNOTEQ = 32;
  public static final int DIVIDE = 38;
  public static final int SUBSTRING = 22;
  public static final int READSTR = 20;
  public static final int GE = 29;
  public static final int CONCATENATE = 21;
  public static final int YADA = 13;
  public static final int READINT = 17;
  public static final int LPAREN = 40;
  public static final int SEMI = 33;
  public static final int MINUS = 36;
  public static final int RPAREN = 41;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int LT = 26;
  public static final int OR = 3;
  public static final int COMMA = 34;
  public static final int BEGIN = 7;
  public static final int LISTE = 45;
  public static final int NUM = 42;
  public static final int PLUS = 35;
  public static final int EXIT = 9;
  public static final int ASSIGN = 24;
  public static final int LE = 27;
  public static final int EOF = 0;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int YAZ = 16;
  public static final int MODE = 39;
  public static final int IDENT = 43;
  public static final int EQ = 25;
  public static final int TIMES = 37;
  public static final int EGER = 10;
  public static final int POSITION = 19;
  public static final int ISE = 11;
  public static final int WHILE = 14;
  public static final int LIST = 23;
  public static final int NE = 30;
  public static final int END = 8;
  public static final int STRING = 44;
  public static final int DEGIL = 12;
  public static final int STREQ = 31;
  public static final int FALSE = 6;
  public static final int GT = 28;
  public static final int LENGTH = 18;
  public static final int DO = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "BEGIN",
  "END",
  "EXIT",
  "EGER",
  "ISE",
  "DEGIL",
  "YADA",
  "WHILE",
  "DO",
  "YAZ",
  "READINT",
  "LENGTH",
  "POSITION",
  "READSTR",
  "CONCATENATE",
  "SUBSTRING",
  "LIST",
  "ASSIGN",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "STREQ",
  "STRNOTEQ",
  "SEMI",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MODE",
  "LPAREN",
  "RPAREN",
  "NUM",
  "IDENT",
  "STRING",
  "LISTE"
  };
}

